name: supervisor_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  retrofit: ^4.4.2
  dio: ^5.3.3
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  internet_connection_checker: ^3.0.1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.2.2
  get_it: ^8.0.3
  lottie: ^2.7.0
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.0.0
  intl: ^0.19.0
  provider: ^6.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  easy_localization: ^3.0.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.5
  analyzer: ^6.4.1
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/supervisor/onboarding1.png
    - assets/images/supervisor/onboarding2.png
    - assets/images/supervisor/onboarding3.png
    - assets/images/supervisor/solid_circle_ic.png
    - assets/images/supervisor/hollow_circle_ic.png
    - assets/images/supervisor/paint_brush.png
    - assets/images/auth/auth_bg.svg
    - assets/images/auth/passwordEye.png
    - assets/images/auth/googleLogo.png
    - assets/images/auth/appleLogo.png
    - assets/images/auth/facebookLogo.png
    - assets/images/auth/microsoftLogo.png
    - assets/json/success.json
    - assets/json/error.json
    - assets/json/loading.json
    - assets/json/empty.json
    - assets/images/supervisor/Omar.png
    - assets/images/supervisor/Reem.png
    - assets/images/supervisor/emergency.png
    - assets/lang/en.json
    - assets/lang/ar.json





